version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: springdb
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: spring-app-container
    ports:
      - "8083:8080"
    depends_on:
      - db
